### ISSUE TITLE
XBRL Class some line-items do not have an accurate +/- when exporting to excel.

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#108]
I am not sure if this is a bug that needs to be looked into more. But when using the XBRL class some of the numbers that are being exported into excel are not properly being identified as a positive or negative number. If you look at Apple 2023 Financial Statements (Consolidated Statements of Cashflows) some of the line items are not accurate. I provided a few below. Is there a fix to this or any idea how this can be addressed? 

us-gaap_OtherNoncashIncomeExpense
us-gaap_PaymentsForRepurchaseOfCommonStock
us-gaap_PaymentsForProceedsFromOtherInvestingActivities

**Comment by dgunning** [comment]
Looking into it

**Comment by dgunning** [comment]
I think I found the issue. Some values require using the calculation file to apply the negative of the number. This was one file I had parsed but hadn't yet applied because I didn't know how to apply the calculation logic. Now I have an idea. This will take a couple of days - I'm running into a busy period, but will try to get it in the next release

**Comment by dgunning** [comment]
Release 2.30.0 with a fix of this issue
