### ISSUE TITLE
XBRL Class some line-items do not have an accurate +/- when exporting to excel. (STILL NOT RIGHT)

### ISSUE THREAD

**Issue by david08-08** [dgunning/edgartools#112]
Hey Dwight- I did an update to the most recent version and I still do not see a fix. There are still some areas that should be negative. Maybe I am looking at it wrong? Please advise. Thank you. 
<img width="1237" alt="Screenshot 2024-09-23 at 1 20 13 PM" src="https://github.com/user-attachments/assets/f3683a43-ffa4-478b-ac49-8239a915e8c8">

**Comment by Colem19** [comment]
Hi David, I think the fix has been applied to the financials. Maybe not to some of the underlying data. That might cause other issues if the fix is to be applied twice.

I get the right signs actually when running this code: 
tenq = Company("aapl").get_filings(form="10-Q")[0].obj()
financials = tenq.financials

financials.get_cash_flow_statement()


![image](https://github.com/user-attachments/assets/e952f2e7-9d76-44e2-9647-40fdb147eb3b)

**Comment by david08-08** [comment]
@Colem19 thank you for your response. Let me ask you a question so I can better understand. There are two classes when pulling financial statements. The XBRL and the TENQ is that accurate? Why is there a discrepancy between the two classes? Is the TENQ-Class supposed to be a more universal version?

**Comment by Colem19** [comment]
XBRL is kind of the raw data format (kind of database). 

TenQ and TenK are actually the financials reports that investor look at.

That’s from my POV.
