### ISSUE TITLE
Missing tickers?

### ISSUE THREAD

**Issue by TristanJanicki** [dgunning/edgartools#136]
I'm using the library (which is great by the way so thank you) to populate a dataset and I'm running into a lot of scenarios where companies are coming back as None

For example:

EG
DAY

and some others.

the code is simply         
`c = Company(ticker)`

and then some code following that depends on it.

Can provide more info upon request but I think this basically sums it up.

**Comment by dgunning** [comment]
Thanks for reporting this. I have found an issue in the CIK lookup. The SEC actually has two CIK/Ticker lookups and one is used as a backup for the other. It turns out that those two tickers are in the backups. I will make a change that will look for the ticker in the merger of the two backups. Will update the ticket when this is done.

**Comment by dgunning** [comment]
This is fixed in version 3.0.2, though 3.0.3 is also now available.

Thanks

**Comment by dgunning** [comment]
Closed as fixed
