### ISSUE TITLE
financials.equity not pulling 10-Q data

### ISSUE THREAD

**Issue by webbsledge** [dgunning/edgartools#149]
When running `financials.equtiy` on AAPL's latest 10-Q filing, no data is returned. This so happens to be the example in the `FinancialStatements.ipynb` but I think running the function within a normal Python script exhibits the same behavior. Perhaps this is an issue with the method using the "instant" API endpoint? I am not sure.

I have attached two screenshots. Note that neither time period at the bottom of the blank statement is highlighted as might be expected. Again, perhaps this is expected behavior with the "instant" endpoint, I am not sure.

<img width="698" alt="Screenshot 2024-11-13 at 11 22 09 PM" src="https://github.com/user-attachments/assets/a11a3373-a32b-4a8c-a49f-f5265bb76e92">
<img width="584" alt="Screenshot 2024-11-13 at 11 23 26 PM" src="https://github.com/user-attachments/assets/f49b6f41-8eb5-42d5-9178-03b16592d8cd">

**Comment by dgunning** [comment]
Should work now.

The root cause is there is filtering logic to only include columns that are not mostly empty. Equity statements tend to be mostly empty. The threshold for mostly empty was **0.7**. The fix moves it to **0.9**.

Long term will have to figure a better way. Removing the filter completely is an option, but there tends to be extraneous periods in the data that have very few values. Also we could split the display logic from the data logic.

**Comment by dgunning** [comment]
Fixed
