### ISSUE TITLE
Missing Fields in Income Statement Facts

### ISSUE THREAD

**Issue by amitgandhinz** [dgunning/edgartools#73]
For some 10Q imports, some facts are missing when querying the facts table.

For example, in the latest 10Q (Q2 2024) for $GD, the 10Q contains rows for Costs of Products and Services (us-gaap:CostOfGoodsAndServicesSold) but this fact is never loaded into the facts table in Edgar-tools or in the income-statement printed.

Likewise for "us-gaap:InterestIncomeExpenseNet" and "us-gaap:OtherNonoperatingIncomeExpense" facts.

This may possibly be related to these fields having a role of "http://fasb.org/us-gaap/role/ref/legacyRef" while most of the facts that do get loaded have a role of "http://www.xbrl.org/2003/role/disclosureRef" 

![image](https://github.com/user-attachments/assets/6c1041c0-3c1b-4f97-a020-6ee9373681bd)

- https://www.sec.gov/ix?doc=/Archives/edgar/data/40533/000004053324000035/gd-20240630.htm

**Comment by dgunning** [comment]
Hey Amit,

I'm working on a rewrite of the XBRL financials the intent of which is to render the data row for row as it is in the financials statements. Here is what it looks like now for General Dynamic 
<img width="650" alt="GDFinancials" src="https://github.com/user-attachments/assets/1468fdb7-3f1c-42b0-a6d2-dc2576333fd5">

It's technically inside of edgartools now, but I need a few more rounds of testing to get it rock solid. I have been incorporating you findings in the new code base so that thanks for that. Should be stable within a week or so

Will keep you posted

**Comment by dgunning** [comment]
Tracking changes on [Financials Extraction from XBRL](https://github.com/dgunning/edgartools/issues/74)
