### ISSUE TITLE
feature: company icon

### ISSUE THREAD

**Issue by benobytes** [dgunning/edgartools#77]
Hi there! Let me just say that this is a truly incredible library, and I appreciate all the hard work you have been putting in. I was actually working on a similar library myself before finding this.

I was wondering what your thoughts on using nonsec data in this library. I have some left over code but thought I would open an issue to ask before making a PR if this would be alright. I would love to contribute and help out!

```py
  async def icon(self) -> bytes | None:
      """
      Tries to retrieve the logo image for the company.

      Returns:
          Optional[bytes]: The logo image as bytes if successful, None otherwise.
      """
      if not self.ticker:
          return None
      try:
          return await get(
              f"https://raw.githubusercontent.com/nvstly/icons/main/ticker_icons/{self.ticker.upper()}.png"
          )
      except HTTPError:
          return None
```

**Comment by dgunning** [comment]
Yeah that would be fine and welcome. A good place would be https://github.com/dgunning/edgartools/blob/main/edgar/reference/tickers.py

We use httpx the only other thing to add would be the retry annotation e.g. 
`@retry(on=httpx.RequestError, attempts=attempts, timeout=retry_timeout, wait_initial=wait_initial)`

See https://github.com/dgunning/edgartools/blob/main/edgar/httprequests.py#L219

We don't need the other annotations since we aren't going to SEC here

**Comment by benobytes** [comment]
Sounds good! I have created a PR at #78.
